### ISSUE TITLE
To-Do List (Milestone 1)

### ISSUE THREAD

**Issue by HarjyotKaur** [UBC-MDS/PySyntext#6]
### Due 05/02/2019
- [x] Function Definitions, Inputs, Outputs, Parameter Lists
- [x] Introduction and Summary 
- [x] Environment : Packages and Requirements

### Due 09/02/2019 
- [x] Test Cases for `TextSummarize` 
- [x] Test Cases for `TextGrams` 
- [x] Test Cases for `TextQuality`
- [x] Function Definition and docstring for `TextSummarize` 
- [x]  Function Definition and docstring for `TextGrams` 
- [x]  Function Definition and docstring for `TextQuality`
- [x] Collaboration and Code of Conduct

**Comment by HarjyotKaur** [comment]
Tasks Completed for Milestone 1
- [x] Function Definitions, Inputs, Outputs, Parameter Lists (@HarjyotKaur )
- [x] Introduction and Summary (@pak-alex)
- [x] Environment : Packages and Requirements (@pak-alex )
- [x] Test Cases for `TextSummarize` (@pak-alex)
- [x] Test Cases for `TextGrams` (@HarjyotKaur)
- [x] Test Cases for `TextQuality` (@HarjyotKaur)
- [x] Function Definition and docstring for `TextSummarize` (@pak-alex)
- [x]  Function Definition and docstring for `TextGrams`  (@HarjyotKaur and @YenanZ)
- [x]  Function Definition and docstring for `TextQuality` (@HarjyotKaur)
- [x] Collaboration and Code of Conduct (@YenanZ)
